### ISSUE TITLE
No docker image and build fails

### ISSUE THREAD

**Issue by nickelswitte** [blaise-io/xssnake#7]
Hello :)

I wanted to spin up the project, but encountered problems.

1. There is no docker image, it does not seem to be public:

```
Error response from daemon: pull access denied for blaise-io/xssnake, 
repository does not exist or may require 'docker login': 
denied: requested access to the resource is denied
```

3. The build fails with the following error message:

```
 => ERROR [app_code 4/5] RUN npm run client.production       9.3s 
------
 > [app_code 4/5] RUN npm run client.production:
#0 1.245
#0 1.245 > xssnake@0.0.1-alpha client.production
#0 1.245 > webpack --mode production --config src/client/webpack.config.ts
#0 1.245
#0 5.927 Error: error:0308010C:digital envelope routines::unsupported
```

What do I need to do to fix it?

Thanks!

**Comment by blaise-io** [comment]
There was a mistake in the Docker image, should be `blaiseio/xssnake`. Fixed in 1efc2c5773a89a7bf9b0e1325856c6f7ec6f5506.

**Comment by nickelswitte** [comment]
Thank you for the correction. I am able to download the docker image and run it, but I only get an empty web page with the following message: `Upgrade Required`.

I cannot find this hardcoded in you code, do you have an idea where this is coming from? 

Anything wrong with my setup? I am using [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy) and the following docker compose:
```
services:
  snake:
    image: blaiseio/xssnake
    container_name: snake
    ports:
      - "8001:8001"
      - "8002:8002"
    restart: always
    environment:
      VIRTUAL_HOST: snake.web.app
      LETSENCRYPT_HOST: snake.web.app
      VIRTUAL_PORT: 8001

networks:
  default:
    name: nginx-proxy
```

**Comment by nickelswitte** [comment]
Ah, and I also checked the logs of the container, but there is nothing related to this.
